#!/usr/bin/env bash
# a script to copy a file to a server

args=("$@")
remotePath="~"

if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    localFile="$1"
    remoteHost="$2"
    remoteUser="$3"
    sshKeyPath="$4"
    scp -o StrictHostKeyChecking=no -i "$sshKeyPath" "$localFile" "$remoteUser@$remoteHost:$remotePath"
fi