#!/usr/bin/env bash
# A script to install Nginx on the server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo chown $USER:$USER /var/www/html/index.nginx-debian.html
sudo chmod 600 /var/www/html/index.nginx-debian.html
echo "Hello World" > /var/www/html/index.nginx-debian.html
service nginx start
