#!/usr/bin/env bash
# A script to install Nginx on the server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw enable
sudo ufw allow 'Nginx HTTP'
sudo su
echo "Hello World!" > /var/www/html/index*
service nginx start
