#!/usr/bin/env bash
# a script to configure the server to redirect user to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw --force enable
sudo ufw allow 'Nginx HTTP'
sudo chown "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod 644 /var/www/html/index.nginx-debian.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo chown "$USER":"$USER" /etc/nginx/sites-available/default
configuration="server {\n
        listen 80 default_server;\n
        listen [::]:80 default_server;\n
        root /var/www/html;\n\n

        index index.html index.htm index.nginx-debian.html;\n\n

        server_name _;\n
        location / {\n
                try_files \$uri \$uri/ =404;\n
        }
        location /redirect_me {\n
            return 301 https://www.alx.com;\n
        }\n
}\n"
echo -e "$configuration" > /etc/nginx/sites-avai*/def*
sudo service nginx --full-restart
