#! /usr/bin/env bash
server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;

        index index.html index.htm index.nginx-debian.html;

        server_name _;
        location / {
                try_files $uri $uri/ =404;
        }
        location /read_me {
            return 301 https://www.alx.com
        }
}