#!/usr/bin/env bash
# A script to install HAProxy

sudo apt-get -y update
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.9
sudo apt-get -y install haproxy=2.9.\*
sudo chown "$USER":"$USER" /etc/default/haproxy
echo "ENABLED=1" > /etc/default/haproxy
CONFIG_ADDS="frontend http-in \n\tbind *:80\n\tdefault_backend app_servers\n\nbackend app_servers\n\tbalance roundrobin\n\tserver 531574-web-01 54.210.57.216:80 check\n\tserver 531574-web-02 54.167.150.28:80 check\n"
sudo chown "$USER":"$USER" /etc/haproxy/haproxy.cfg
echo -e "$CONFIG_ADDS" >> /etc/haproxy/haproxy.cfg
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable
sudo service haproxy --full-restart

