#!/usr/bin/env bash
# This scipt is displaying "Best School" 10 times
# For the 9th interation, also Hi on a new line
while ((i <= 10))
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
        echo "Hi"
    fi
    i=$((i + 1))
done