#!/usr/bin/env bash
# This scipt is displaying "Best School" 10 times
# bad luck - 4th goodluck - 8th 
i=1
while ((i <= 10))
do
    if [ "$i" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i + 1))
done