#!/usr/bin/env bash
# This scipt is displaying "Best School" 10 times
# bad luck - 4th goodluck - 8th 
i=1
while ((i <= 20))
do
    echo "$i"
    case $i in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    i=$((i + 1))
done